//! CDP-level backend operations (Layer 2 — daemon-internal).
//!
//! [`BackendOp`] represents the primitives that the daemon's Action Handler
//! compiles high-level [`Action`](super::action::Action)s into. These are
//! executed by a [`BackendSession`] implementation (Local, Extension, Cloud).
//!
//! BackendOps are **not** exposed to CLI clients and do **not** need serde.
//! The daemon owns the full lifecycle: compile Action -> sequence of BackendOps
//! -> execute via backend -> aggregate into ActionResult.

/// A CDP-level primitive operation executed against a browser backend.
///
/// The Action Handler compiles user-facing Actions into sequences of these ops.
/// For example, `Action::Click { selector }` compiles to:
/// ```text
/// GetDocument -> QuerySelector(selector) -> GetBoxModel(node_id) -> DispatchMouseEvent(x, y)
/// ```
#[derive(Debug, Clone)]
pub enum BackendOp {
    // ---- Navigation ----
    /// Navigate a target to a URL (`Page.navigate`).
    Navigate {
        /// CDP target ID.
        target_id: String,
        url: String,
    },

    // ---- JavaScript evaluation ----
    /// Evaluate a JS expression (`Runtime.evaluate`).
    Evaluate {
        target_id: String,
        expression: String,
        /// If true, evaluate returns by value (no remote object).
        return_by_value: bool,
    },

    // ---- DOM queries ----
    /// Get the document root node (`DOM.getDocument`).
    GetDocument { target_id: String },

    /// Query a CSS selector within a node (`DOM.querySelector`).
    QuerySelector {
        target_id: String,
        node_id: i64,
        selector: String,
    },

    /// Get the box model (position/size) of a node (`DOM.getBoxModel`).
    #[allow(dead_code)]
    GetBoxModel { target_id: String, node_id: i64 },

    // ---- Input dispatch ----
    /// Dispatch a mouse event (`Input.dispatchMouseEvent`).
    DispatchMouseEvent {
        target_id: String,
        /// Event type: "mousePressed", "mouseReleased", "mouseMoved".
        event_type: String,
        x: f64,
        y: f64,
        /// Mouse button: "left", "right", "middle".
        button: String,
        /// Number of clicks.
        click_count: i32,
    },

    /// Dispatch a key event (`Input.dispatchKeyEvent`).
    DispatchKeyEvent {
        target_id: String,
        /// Event type: "keyDown", "keyUp", "char".
        event_type: String,
        /// Key identifier (e.g. "Enter", "a").
        key: String,
        /// Text generated by the key press.
        text: String,
    },

    // ---- Capture ----
    /// Capture a screenshot as PNG (`Page.captureScreenshot`).
    CaptureScreenshot {
        target_id: String,
        /// Capture the full scrollable page (not just the viewport).
        full_page: bool,
    },

    /// Print the page to PDF (`Page.printToPDF`).
    PrintToPdf { target_id: String },

    /// Get the accessibility tree (`Accessibility.getFullAXTree`).
    GetAccessibilityTree { target_id: String },

    // ---- Cookies ----
    /// Get all cookies (`Network.getCookies`).
    GetCookies { target_id: String },

    /// Set a cookie (`Network.setCookie`).
    SetCookie {
        target_id: String,
        name: String,
        value: String,
        domain: String,
        path: String,
        secure: Option<bool>,
        http_only: Option<bool>,
        same_site: Option<String>,
        expires: Option<f64>,
    },

    /// Delete cookies matching criteria (`Network.deleteCookies`).
    DeleteCookies {
        target_id: String,
        name: String,
        /// Optional domain filter.
        domain: Option<String>,
        /// Optional path filter.
        path: Option<String>,
    },

    /// Get the DOM node at a specific page coordinate (`DOM.getNodeForLocation`).
    #[allow(dead_code)]
    GetNodeForLocation { target_id: String, x: i64, y: i64 },

    // ---- DOM manipulation ----
    /// Focus a DOM node (`DOM.focus`).
    #[allow(dead_code)]
    DomFocus { target_id: String, node_id: i64 },

    /// Set files on a file input element (`DOM.setFileInputFiles`).
    SetFileInputFiles {
        target_id: String,
        node_id: i64,
        files: Vec<String>,
    },

    // ---- Target management ----
    /// List all CDP targets (`Target.getTargets`).
    #[allow(dead_code)]
    GetTargets,

    /// Create a new target/tab (`Target.createTarget`).
    CreateTarget {
        url: String,
        /// If set, open in this browser window.
        #[allow(dead_code)]
        window_id: Option<i64>,
        /// If true, create in a new window.
        new_window: bool,
    },

    /// Close a target (`Target.closeTarget`).
    CloseTarget { target_id: String },
}

impl BackendOp {
    /// Extract the target_id from this operation, if it has one.
    pub fn target_id(&self) -> Option<&str> {
        match self {
            BackendOp::Navigate { target_id, .. }
            | BackendOp::Evaluate { target_id, .. }
            | BackendOp::GetDocument { target_id }
            | BackendOp::QuerySelector { target_id, .. }
            | BackendOp::GetBoxModel { target_id, .. }
            | BackendOp::DispatchMouseEvent { target_id, .. }
            | BackendOp::DispatchKeyEvent { target_id, .. }
            | BackendOp::CaptureScreenshot { target_id, .. }
            | BackendOp::PrintToPdf { target_id }
            | BackendOp::GetAccessibilityTree { target_id }
            | BackendOp::GetCookies { target_id }
            | BackendOp::SetCookie { target_id, .. }
            | BackendOp::DeleteCookies { target_id, .. }
            | BackendOp::GetNodeForLocation { target_id, .. }
            | BackendOp::DomFocus { target_id, .. }
            | BackendOp::SetFileInputFiles { target_id, .. }
            | BackendOp::CloseTarget { target_id } => Some(target_id),
            BackendOp::GetTargets | BackendOp::CreateTarget { .. } => None,
        }
    }

    /// Whether this operation targets a specific page and needs a flattened
    /// CDP session (sessionId) to route correctly over a browser-level WS.
    pub fn is_page_scoped(&self) -> bool {
        matches!(
            self,
            BackendOp::Navigate { .. }
                | BackendOp::Evaluate { .. }
                | BackendOp::GetDocument { .. }
                | BackendOp::QuerySelector { .. }
                | BackendOp::GetBoxModel { .. }
                | BackendOp::DispatchMouseEvent { .. }
                | BackendOp::DispatchKeyEvent { .. }
                | BackendOp::CaptureScreenshot { .. }
                | BackendOp::PrintToPdf { .. }
                | BackendOp::GetAccessibilityTree { .. }
                | BackendOp::GetCookies { .. }
                | BackendOp::SetCookie { .. }
                | BackendOp::DeleteCookies { .. }
                | BackendOp::GetNodeForLocation { .. }
                | BackendOp::DomFocus { .. }
                | BackendOp::SetFileInputFiles { .. }
        )
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn navigate_debug_format() {
        let op = BackendOp::Navigate {
            target_id: "ABC123".into(),
            url: "https://example.com".into(),
        };
        let debug = format!("{op:?}");
        assert!(debug.contains("Navigate"));
        assert!(debug.contains("ABC123"));
    }

    #[test]
    fn clone_works() {
        let op = BackendOp::Evaluate {
            target_id: "T1".into(),
            expression: "1+1".into(),
            return_by_value: true,
        };
        let cloned = op.clone();
        match cloned {
            BackendOp::Evaluate {
                expression,
                return_by_value,
                ..
            } => {
                assert_eq!(expression, "1+1");
                assert!(return_by_value);
            }
            _ => panic!("wrong variant after clone"),
        }
    }

    #[test]
    fn dispatch_mouse_event_fields() {
        let op = BackendOp::DispatchMouseEvent {
            target_id: "T1".into(),
            event_type: "mousePressed".into(),
            x: 150.0,
            y: 300.0,
            button: "left".into(),
            click_count: 1,
        };
        match op {
            BackendOp::DispatchMouseEvent {
                x, y, click_count, ..
            } => {
                assert!((x - 150.0).abs() < f64::EPSILON);
                assert!((y - 300.0).abs() < f64::EPSILON);
                assert_eq!(click_count, 1);
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn create_target_with_window() {
        let op = BackendOp::CreateTarget {
            url: "about:blank".into(),
            window_id: Some(42),
            new_window: false,
        };
        match op {
            BackendOp::CreateTarget {
                url,
                window_id,
                new_window,
            } => {
                assert_eq!(url, "about:blank");
                assert_eq!(window_id, Some(42));
                assert!(!new_window);
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn target_id_returns_some_for_page_ops() {
        let op = BackendOp::Navigate {
            target_id: "T1".into(),
            url: "https://example.com".into(),
        };
        assert_eq!(op.target_id(), Some("T1"));
    }

    #[test]
    fn target_id_returns_none_for_browser_ops() {
        assert!(BackendOp::GetTargets.target_id().is_none());
        let op = BackendOp::CreateTarget {
            url: "about:blank".into(),
            window_id: None,
            new_window: false,
        };
        assert!(op.target_id().is_none());
    }

    #[test]
    fn is_page_scoped_true_for_page_commands() {
        let op = BackendOp::Evaluate {
            target_id: "T1".into(),
            expression: "1+1".into(),
            return_by_value: true,
        };
        assert!(op.is_page_scoped());
    }

    #[test]
    fn is_page_scoped_false_for_target_management() {
        assert!(!BackendOp::GetTargets.is_page_scoped());
        let op = BackendOp::CloseTarget {
            target_id: "T1".into(),
        };
        assert!(!op.is_page_scoped());
    }
}
