name: ✨ Feature Request
description: Suggest a new feature or enhancement for Actionbook
title: "[Feature]: "
labels: ["enhancement", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature.
        Keep it short; we can refine details during discussion.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Currently, when working with Actionbook...
        This causes issues because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
      placeholder: |
        I would like to see a new feature that...
        This would work by...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Target Component (Optional)
      description: Which component should this feature be added to?
      options:
        - "SDK (@actionbookdev/sdk)"
        - "MCP Server (@actionbookdev/mcp)"
        - "Action Builder"
        - "Knowledge Builder"
        - "API Service"
        - "Database (services/db)"
        - "Website (apps/website)"
        - "Documentation"
        - "Platform-wide"
        - "Other"
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases (Optional)
      description: Where would this help the most?
      placeholder: Describe one or two real scenarios
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Optional)
      description: Any links, screenshots, or examples
      placeholder: Share anything else useful
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to implement this feature and submit a PR
          required: false
